Repository MiniProject-2/need-more-task-be, pull requests merged in 2023-05, with the labels that each got.

#1 feat: create Task entity
  src/main/java/com/task/needmoretask/model/Task.java
Labels: enhancement

#2 fix: task add to title, description
  src/main/java/com/task/needmoretask/controller/TaskController.java
  src/main/java/com/task/needmoretask/controller/temp
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/main/java/com/task/needmoretask/service/temp
Labels: enhancement

#3 fix: move to Task package
  src/main/java/com/task/needmoretask/model/Task.java
Labels: hotfix

#8 fix: user role type change jwt, email to username
  src/main/java/com/task/needmoretask/core/auth/jwt/MyJwtAuthorizationFilter.java
  src/main/java/com/task/needmoretask/core/auth/jwt/MyJwtProvider.java
  src/main/java/com/task/needmoretask/core/auth/session/MyUserDetails.java
  src/main/java/com/task/needmoretask/core/auth/session/MyUserDetailsService.java
  src/main/java/com/task/needmoretask/model/user/User.java
  src/main/java/com/task/needmoretask/model/user/UserRepository.java
Labels: enhancement

#10 feat: 1차 대시보드 getLatestTasks 완료
  src/main/java/com/task/needmoretask/controller/TaskController.java
  src/main/java/com/task/needmoretask/core/advice/MyLogAdvice.java
  src/main/java/com/task/needmoretask/dto/task/TaskResponse.java
  src/main/java/com/task/needmoretask/model/assign/AssignRepository.java
  src/main/java/com/task/needmoretask/model/assign/Assignment.java
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
Labels: enhancement

#14 feat: add Task Create, Test
  build.gradle
  src/main/java/com/task/needmoretask/controller/TaskController.java
  src/main/java/com/task/needmoretask/dto/task/TaskRequest.java
  src/main/java/com/task/needmoretask/dto/task/TaskResponse.java
  src/main/java/com/task/needmoretask/model/assign/AssignRepository.java
  src/main/java/com/task/needmoretask/model/assign/Assignment.java
  src/main/java/com/task/needmoretask/model/profile/Profile.java
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
  src/main/java/com/task/needmoretask/model/temp
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
  src/test/java/com/task/needmoretask/service/TaskServiceTest.java
Labels: enhancement

#15 fix: remove User @Column(nullable), edit TaskRepository
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
Labels: hotfix

#18 feat: add Task Update, Integration Test
  src/main/java/com/task/needmoretask/controller/TaskController.java
  src/main/java/com/task/needmoretask/dto/task/TaskResponse.java
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
Labels: enhancement

#21 fix: Timestamped type change LocalDateTime to ZonedDateTime
  build.gradle
  src/main/java/com/task/needmoretask/NeedMoreTaskApplication.java
  src/main/java/com/task/needmoretask/controller/TaskController.java
  src/main/java/com/task/needmoretask/core/util/Timestamped.java
  src/main/java/com/task/needmoretask/dto/task/TaskRequest.java
  src/main/java/com/task/needmoretask/dto/task/TaskResponse.java
  src/main/java/com/task/needmoretask/model/assign/AssignRepository.java
  src/main/java/com/task/needmoretask/model/assign/Assignment.java
  src/main/java/com/task/needmoretask/model/task/Task.java
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
  src/test/java/com/task/needmoretask/repository/TaskRepositoryTest.java
  src/test/java/com/task/needmoretask/service/TaskServiceTest.java
Labels: hotfix

#23 fix: LocaldateTime -> ZonedDateTime 으로 변경
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/repository/TaskRepositoryTest.java
Labels: duplicate

#34 merge 'feature/user' into 'dev'
  .gitignore
  build.gradle
  src/main/java/com/task/needmoretask/NeedMoreTaskApplication.java
  src/main/java/com/task/needmoretask/controller/UserController.java
  src/main/java/com/task/needmoretask/core/auth/jwt/MyJwtAuthorizationFilter.java
  src/main/java/com/task/needmoretask/core/auth/jwt/MyJwtProvider.java
  src/main/java/com/task/needmoretask/core/auth/session/MyUserDetails.java
  src/main/java/com/task/needmoretask/core/config/JwtLogoutHandler.java
  src/main/java/com/task/needmoretask/core/config/MySecurityConfig.java
  src/main/java/com/task/needmoretask/core/config/S3Config.java
  src/main/java/com/task/needmoretask/core/util/MyFileUtil.java
  src/main/java/com/task/needmoretask/core/util/S3Uploader.java
  src/main/java/com/task/needmoretask/dto/user/UserRequest.java
  src/main/java/com/task/needmoretask/dto/user/UserResponse.java
  src/main/java/com/task/needmoretask/model/auth/Auth.java
  src/main/java/com/task/needmoretask/model/auth/AuthRepository.java
  src/main/java/com/task/needmoretask/model/log/Log.java
  src/main/java/com/task/needmoretask/model/log/LogRepository.java
  src/main/java/com/task/needmoretask/model/user/User.java
  src/main/java/com/task/needmoretask/model/user/UserRepository.java
  src/main/java/com/task/needmoretask/service/UserService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
  src/test/java/com/task/needmoretask/controller/UserControllerTest.java
Labels: enhancement

#38 fix: change getUsers, searchUsers responseDTO
  src/main/java/com/task/needmoretask/dto/user/UserResponse.java
  src/main/java/com/task/needmoretask/service/UserService.java
Labels: hotfix

#55 fix: reset to cors config
  src/main/java/com/task/needmoretask/core/config/MySecurityConfig.java
Labels: hotfix

#58 fix: create, update Task request startAt must be before endAt
  src/main/java/com/task/needmoretask/dto/task/TaskRequest.java
Labels: hotfix

#61 fix: auth token save, logout
  src/main/java/com/task/needmoretask/core/auth/jwt/MyJwtProvider.java
  src/main/java/com/task/needmoretask/core/util/S3Uploader.java
Labels: hotfix

#62 fix: getUsers add isValidRole method
  src/main/java/com/task/needmoretask/service/UserService.java
Labels: hotfix

#66 feat: overview add countQuery to taskProgress
  src/main/java/com/task/needmoretask/dto/task/TaskResponse.java
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/service/TaskServiceTest.java
Labels: enhancement

#68 feat: overview repo쿼리 조건추가
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
  src/test/java/com/task/needmoretask/service/TaskServiceTest.java
Labels: enhancement

#69 feat: overview repo쿼리 조건추가
  src/main/java/com/task/needmoretask/model/task/TaskJPQLRepository.java
  src/main/java/com/task/needmoretask/service/TaskService.java
  src/test/java/com/task/needmoretask/controller/TaskControllerTest.java
  src/test/java/com/task/needmoretask/service/TaskServiceTest.java
Labels: enhancement

#70 fix: overview countQuery수정
  src/main/java/com/task/needmoretask/model/task/TaskRepository.java
Labels: enhancement

#73 docs: Update README.md
  README.md
Labels: documentation

#74 fix: update ERD highlight
  README.md
Labels: documentation

#76 fix: CORS
  src/main/java/com/task/needmoretask/core/config/MySecurityConfig.java
Labels: hotfix
